### ISSUE TITLE
[BUG] - BSOD with AudFilter.sys on W11 22631.2861

### ISSUE THREAD

**Issue by cocus** [n00b69/woa-polaris#8]
### Description

Hi, just flashed the 22631.2861, followed the instructions to the letter, but once it reboots the first time on windows, it says "getting your devices ready", and after a short while, it bsods with a thread error caused by AudFilter.sys. My device is a Mix2s 256GB (from china). I was able to run W11 before using the other instructions on the renegade project, but of course, no audio. Knowing this bsod is caused by "audfilter" I'm pretty sure it has something to do with it.
What can I do? Should I pick a different OS? (I've selected W11 22631.2861, Client, Spanish).

### Reproduction steps

```bash
Follow the steps on your guide, until windows first boots. Didn't deviate anything from it.
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
These drivers are quite problematic to be honest, the solution should be;

1) Use the "polaris-old.zip" drivers
2) Use the old UEFI
3) Boot windows
4) Then update drivers and UEFI

**Comment by TrustedFloppa** [comment]
Honestly, you should use polaris-old drivers as sog mentioned above cause audio drivers are bsoding during windeploy. I have no actual idea how to fix them. So for now stick with old drivers.
